---CREATING THE DATABASE
CREATE DATABASE AIRLINE_RESERVATION;


--CREATING VARIOUS RELATIONS FROM RELATION MAPPING DIAGRAM
CREATE TABLE AIRPORT(
    AIRPORT_CODE VARCHAR(25),
    AIRPORT_NAME VARCHAR(100)  NOT NULL,
    LOCATION  VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    STATE VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    ZIP INT NOT NULL,
    CONSTRAINT AIRPORT_PK PRIMARY KEY (AIRPORT_CODE));

CREATE TABLE AIRLINE_COMAPNY(
  COMPANY_ID VARCHAR(25),
  COMPANY_NAME VARCHAR(50) NOT NULL,
  CONSTRAINT  AIRLINE_COMAPANY_PK PRIMARY KEY (COMPANY_ID));

CREATE TABLE AIRPLANE(
    AIRPLANE_NO  VARCHAR(20),
    SEATING_CAPACITY  INT NOT NULL,
    COMPANY VARCHAR(30)  NOT NULL,
    CONSTRAINT  AIRPLANE_PK PRIMARY KEY (AIRPLANE_NO),
    CONSTRAINT  COMPANY_PLANE_FK FOREIGN KEY(COMPANY) REFERENCES AIRLINE_COMAPNY(COMPANY_ID));


CREATE TABLE PLANE_PORT_ACCESS(
    AIRPORT VARCHAR(30) NOT NULL ,
    AIRPLANE VARCHAR(30) NOT NULL,
    PRIMARY KEY (AIRPLANE,AIRPORT),
    CONSTRAINT  ACCESS_PORT_FK FOREIGN KEY(AIRPORT) REFERENCES AIRPORT(AIRPORT_CODE) ON DELETE  CASCADE ,
    CONSTRAINT  ACCESS_PLANE_FK FOREIGN KEY(AIRPLANE) REFERENCES AIRPLANE(AIRPLANE_NO) ON DELETE CASCADE
);

CREATE TABLE SEAT(
    AIRPLANE VARCHAR(30),
    SEAT_NO VARCHAR(5),
    AVAILABILITY VARCHAR(10) DEFAULT 'TRUE',
    LOCATION VARCHAR(25) NOT NULL,
    SEAT_CLASS VARCHAR(25) NOT NULL,
    CONSTRAINT SEAT_PK PRIMARY kEY (AIRPLANE,SEAT_NO),
    CONSTRAINT SEAT_PLANE_FK FOREIGN KEY (AIRPLANE) REFERENCES AIRPLANE(AIRPLANE_NO) ON DELETE CASCADE
);

CREATE TABLE  END_USER(
    EMAIL VARCHAR(50),
    FNAME VARCHAR(30) NOT NULL,
    LNAME VARCHAR(30) NOT NULL,
    PHONE INT,
    TYPE_OF_USER VARCHAR(30) NOT NULL,
    CONSTRAINT  USER_PK PRIMARY KEY (EMAIL)
);

CREATE TABLE FLIGHT_TRIP(
    FLIGHT_TRIP_ID VARCHAR(30),
    NO_OF_TRAVELLERS INT NOT NULL,
    ARRIVAL_AIRPORT VARCHAR(30) NOT NULL ,
    ARRIVAL_TIME DATE NOT NULL ,
    DEPART_AIRPORT VARCHAR(30) NOT NULL,
    DEPART_TIME  DATE NOT NULL ,
    USER_EMAIL VARCHAR(30) NOT NULL,
    CONSTRAINT FLIGHT_TRIP_PK PRIMARY KEY (FLIGHT_TRIP_ID),
    CONSTRAINT FLIGHT_TRIP_USER_FK FOREIGN KEY (USER_EMAIL) REFERENCES END_USER(EMAIL) ON DELETE SET NULL
);
CREATE TABLE FARE(
    FLIGHT_TRIP_ID VARCHAR(15) ,
    FINAL_AMOUNT DECIMAL(9,2) NOT NULL,
    AMOUNT DECIMAL(9,2) NOT NULL,
    CURRENCY VARCHAR(5) NOT NULL,
    DISCOUNT DECIMAL(4,2) NOT NULL,
    TAX DECIMAL(5,2) NOT NULL,
    CONSTRAINT FARE_PK PRIMARY KEY (FLIGHT_TRIP_ID),
    CONSTRAINT FARE_FLT_TRIP_FK FOREIGN KEY (FLIGHT_TRIP_ID) REFERENCES FLIGHT_TRIP(FLIGHT_TRIP_ID) ON DELETE CASCADE
);

CREATE TABLE TRAVELLER(
    TRAVELLER_ID VARCHAR(30),
    FNAME VARCHAR(30) NOT NULL ,
    PHONE INT ,
    LNAME VARCHAR(30) NOT NULL,
    CONSTRAINT TRAVELLER_PK PRIMARY KEY (TRAVELLER_ID)
);

CREATE TABLE TRAVELLER_ITENARY(
    FLIGHT VARCHAR(30) ,
    ID VARCHAR(30) NOT NULL,
    AIRPLANE VARCHAR(30),
    SEAT_NO VARCHAR(30),
    CONSTRAINT TRAVELLER_ITENARY_PK PRIMARY KEY (FLIGHT,AIRPLANE,SEAT_NO),
    CONSTRAINT  TRAVELLER_FLIGHT_TRIP_FK FOREIGN KEY (FLIGHT) REFERENCES FLIGHT_TRIP(FLIGHT_TRIP_ID) ON DELETE CASCADE ,
    CONSTRAINT  TRAVELLER_SEAT_FK FOREIGN KEY (AIRPLANE,SEAT_NO) REFERENCES SEAT(AIRPLANE,SEAT_NO),
    CONSTRAINT TRAVELLER_ID_FK FOREIGN KEY (ID) REFERENCES TRAVELLER(TRAVELLER_ID)
);


CREATE TABLE HOP(
    HOP_ID VARCHAR(30),
    DISTANCE DECIMAL(5,2) NOT NULL ,
    BASE_FARE DECIMAL(9,2) NOT NULL ,
    AIRPLANE VARCHAR(30) NOT NULL ,
    ARRIVAL_AIRPORT VARCHAR(30) NOT NULL,
    ARRIVAL_TIME DATE NOT NULL,
    DEPART_AIRPORT VARCHAR(30) NOT NULL,
    DEPART_TIME DATE NOT NULL,
    CONSTRAINT HOP_PK PRIMARY KEY (HOP_ID),
    CONSTRAINT HOP_AIRPLANE_FK FOREIGN KEY (AIRPLANE) REFERENCES AIRPLANE(AIRPLANE_NO),
    CONSTRAINT HOP_ARRIVAL_FK FOREIGN KEY (ARRIVAL_AIRPORT) REFERENCES  AIRPORT(AIRPORT_CODE),
    CONSTRAINT HOP_DEPART_FK FOREIGN KEY (DEPART_AIRPORT) REFERENCES  AIRPORT(AIRPORT_CODE)
);

CREATE TABLE HAS(
    HOP VARCHAR(30) ,
    FLIGHT_TRIP VARCHAR(30) ,
    CONSTRAINT HAS_PK PRIMARY KEY (HOP,FLIGHT_TRIP),
    CONSTRAINT HAS_HOP_FK FOREIGN KEY (HOP) REFERENCES HOP(HOP_ID),
    CONSTRAINT HAS_FLIGHT_FK FOREIGN KEY (FLIGHT_TRIP) REFERENCES FARE(FLIGHT_TRIP_ID) ON DELETE CASCADE
);
